// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/Alvarios/guards/config"
	"github.com/Alvarios/guards/guards"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeEvent() Server {
	logConfig := config.NewConfig()
	logger := guards.NewLogger(logConfig)
	guardsGuards := guards.NewGuards(logger)
	router := mux.NewRouter()
	server := NewServer(guardsGuards, router)
	return server
}
